export const SET_POPULAR = 'SET_POPULAR'
export const GET_POPULAR_REQUEST = 'GET_POPULAR_REQUEST'
export const GET_POPULAR_SUCCESS = 'GET_POPULAR_SUCCESS'
export const GET_POPULAR_FAIL = 'GET_POPULAR_FAIL'